### ISSUE TITLE
Online samples from Readme page don't work in latest Safari (9.0.1) with plugin installed

### ISSUE THREAD

**Issue by kooler** [sarandogou/webrtc-everywhere#59]
Throws an error: 
```
TypeError: getPlugin().getUserMedia is not a function. (In 'getPlugin().getUserMedia(constraints, successCallback, errorCallback)', 'getPlugin().getUserMedia' is undefined)
```

**Comment by DoubangoTelecom** [comment]
The plugin isn't signed by a certificate, check https://github.com/sarandogou/webrtc-everywhere#known-issues, this may be the issue

**Comment by kooler** [comment]
Yes, that was the problem. Thanks.

**Comment by Ivan-Feofanov** [comment]
In Safari 9.0.3 your plugin do not send request and i can not add it to browser security list. On your example site i get same error - getUserMEdia is not a function.
